language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo clean && hexo g
  - cd ./public
  - git init
  - git config user.name "ronething-bot"
  - git config user.email "admin@ronething.cn"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master


# after_script:
#   - cd ../
#   - chmod +x ./bin/autoissue
#   - ./bin/autoissue
# E: Build LifeCycle
#
notifications:
  webhooks:
    secure: "KCGzhWkRTiZDAB8a6E1yE/RQofW1dIBj6g32SlHxoIgKb2Z43T19ud0L6GJIhlEG19ZiPtAZ5hvSuJUrQkuvBtHH152Ax2tKc+m2Dybcw0RIhyzmlZ333EGPowA0ZYtkz9zpU6WaGDhUWbzjontfdyECDc9lCOnJ/WkoMugsgQR4Rku9yQVfGslZTeJXOqUol9bFfxY53YAdb1mZZQkmUxM/Oq6pUmXduFkN6FDDk4hcZM3nhP5rWvoPJHmGtcFfSFlMlh1fdqFlJzjqodECzgR3XJg/ms9uo/RkH/fA/a6EfbMBJniNId5ecdc7qpzyPeJHcASu/+nSP9uUwNv0sCDB+MJStsC5vfJee6A6OsEbupyDy8dfgIWd1tJtmfL6XI3pPecqMgi97RyJ0Uu9RyO9G1yjeH/nXMuHMeHoApvUnjVeftDgwtx0LDUmWOaYrvowWf085+tOksckFu6hotUYgarpW75vDh0Ti8vLmZXt6oJuglz7PSImJdfGBej3IcD5EIqIiQfcdsookCrD6DFPxzEdliUb4zTmFe0vq4+BetlZ7o7afeeU7Ar9ERIVWdVLrbuf3Uwe1TQFiV70AA8VucOHElzPSRgocyxlvbbmobFREP5xgXbln2ovJCovVbhdPQxw/WZ0Uz3CJQlBwZV8+5UI0AIWqZeJEORwMtk="

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/ronething/ronething.github.io.git
