language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo clean && hexo g
  - cd ./public
  - git init
  - git config user.name "ronething-bot"
  - git config user.email "admin@ronething.cn"
  - git add .
  - git commit -m "update blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master


# after_script:
#   - cd ../
#   - chmod +x ./bin/autoissue
#   - ./bin/autoissue
# E: Build LifeCycle
#
notifications:
  webhooks:
    secure: "VPT6c0doT+19duKFUA1EDN0T4rkcOPktAmqFnZ8BkkCNdEh3/ziFxajjWyUnmvFLH7dqWBP5jWBZLsy5vLFah0OjKFioOS9mf9Vw8UKOnXusug32RKLxr8dOFax+rndYT43i/KStD8vPQ78Hh5kg+eRUYZyEEytfGnTIT76FnM+unSl3kJYVi+pnoLEntqhVT7Hlqt36V46BZF/CEnftdD9xWRONsCtA1mPdoopx3GwPcIZyeHdthjASJS70LzuVEWyeRvPlWxEy+jREeb94Z2SksM3kGyN335VzcnBvA0wUcXD+DHYAhrcPsA0hzXbEUwUAmO0goCn26FXG2LjAIfm6pmPA2ChRG+dI84I1GZ1/xSSsZBGIQ5hXOx7MKlWLWKWpvHXJ5zzhUnHFx4kvhEDvDzCg1xryINQ6XkAgQuUU9Ab8l/NGiZtyT1Gs+k8xy752B3ZXYzicexUrpC1kJCna8+E1g6ooureafxUERD9RZGkNfQqLIVTrVH9/58lS+hzb2EdIy3kbrKFQIg6YBUM0jwGeItyxzCkOdxBMaomAPC8ZRJHqTWHz9lflpORsPJm0iwUp8pU9cTFKxjcdycWD7t4QD5lhd1FkNSFzvgPZ/JfohBpOeRrsKuq+vvV0VvAOc2tIW1ViF81U1GgyvYx1A0hPl5xN5jgalO5Nt+M="

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com/ronething/ronething.github.io.git
